### ISSUE TITLE
What is written in the comment is to multiply ALL_SIDED , but it is actually multiplied by PROJ_LAI

### ISSUE THREAD

**Issue by WYPZL** [hollorol/RBBGCMuso#10]
conduct_calc.c

	/* Leaf conductance to sensible heat, per unit all-sided LAI */
	gl_sh = gl_bl;
	
	/* Canopy conductance to evaporated water vapor */
	gc_e_wv = gl_e_wv * epv->proj_lai;
	
	/* Canopy conductane to sensible heat */
	gc_sh = gl_sh * epv->proj_lai;

**Comment by hollorol** [comment]
The issue had been answered in the original Biome-BGC repository. 
 
https://github.com/bpbond/Biome-BGC/issues/3
