### ISSUE TITLE
Error with musoSensi

### ISSUE THREAD

**Issue by 857687671** [hollorol/RBBGCMuso#13]
Hello,I used the sample data and my own data for sensitivity analysis according to the description of RBBGCMuso, but I don't know why there is such an error prompt,thank you.
library(RBBGCMuso)
> setwd("D:/F8_BGC_R")
> parameters <- read.csv("parameters.csv")
> musoSensi(iterations = 10000, varIndex = 2)
[1] 1
Error in ans[npos] <- rep(no, length.out = len)[npos] :replacement has length zero
> musoMonte(parameters=parameters,iterations=1000,varIndex=8)
[1] 1
Error in ans[npos] <- rep(no, length.out = len)[npos] : replacement has length zero
>

**Comment by hollorol** [comment]
Hello, thanks for reporting the issue. 

Can you run the model, with runMuso() function, or calibMuso() function?

What are in your output section in your ini File? What is the content of your parameters.csv?

**Comment by 857687671** [comment]
Hello, thanks for your quick response.&nbsp;
I can run this model successfully with runMuso() function.
These two attachments are my ini File（this file is modified from the sample file） and parameters.csv(this file is copied from the sample file).
Thanks again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hollorol/RBBGCMuso"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 晚上9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hollorol/RBBGCMuso] Error with musoSensi (#13)





 
Hello, thanks for reporting the issue.
 
Can you run the model, with runMuso() function, or calibMuso() function?
 
What are in your output section in your ini File? What is the content of your parameters.csv?

**Comment by hollorol** [comment]
Thank you very much. I cannot see the attached files (maybe github did not allow it via email). You can attache these files in github, in the comment section.

**Comment by 857687671** [comment]
Hello, thanks for your quick response.
I uploaded a compressed file containing  my ini File（this file is modified from the sample file） and parameters.csv(this file is copied from the sample file).
Thanks again.


[ini+par.zip](https://github.com/hollorol/RBBGCMuso/files/6473626/ini%2Bpar.zip)

**Comment by hollorol** [comment]
Thanks! I'll look at it as soon as possible

**Comment by hollorol** [comment]
What is the output of this:
```
setwd("D:/F8_BGC_R")
parameters <- read.csv("parameters.csv")
musoSensi(iterations = 10000, varIndex = 2)
traceback()
```
It would help a lot

**Comment by 857687671** [comment]
> library(RBBGCMuso)
[1] "This is RBBGCMuso version 0.7"
> setwd("D:/F8_BGC_R")
> parameters <- read.csv("parameters.csv")
> musoSensi(iterations = 10000, varIndex = 2)
[1] 1
Error in ans[npos] <- rep(no, length.out = len)[npos] : 更换参数长度为零
> traceback()
7: ifelse(iterations < 3000, 3000, NULL)
6: limSolve::xsample(G = G, H = h, E = E, F = f, burninlength = burnin, 
       iter = iterations)
5: withCallingHandlers(expr, warning = function(w) if (inherits(w, 
       classes)) tryInvokeRestart("muffleWarning"))
4: suppressWarnings(limSolve::xsample(G = G, H = h, E = E, F = f, 
       burninlength = burnin, iter = iterations))
3: musoRand(parameters = parameters, fileType = "epc", iterations = iterations)
2: musoMonte(parameters = parameters, settings = settings, inputDir = inputDir, 
       outLoc = outLoc, iterations = iterations, preTag = preTag, 
       outputType = outputType, outVars = outVars, fun = fun, varIndex = varIndex, 
       skipSpinup = skipSpinup, skipZero = skipZero, postProcString = postProcString, 
       modifyOut = modifyOut)
1: musoSensi(iterations = 10000, varIndex = 2)

**Comment by 857687671** [comment]
Thanks a lot!  These are the outputs:

> library(RBBGCMuso)
[1] "This is RBBGCMuso version 0.7"
> setwd("D:/F8_BGC_R")
> parameters <- read.csv("parameters.csv")
> musoSensi(iterations = 10000, varIndex = 2)
[1] 1
Error in ans[npos] <- rep(no, length.out = len)[npos] : 更换参数长度为零
> traceback()
7: ifelse(iterations < 3000, 3000, NULL)
6: limSolve::xsample(G = G, H = h, E = E, F = f, burninlength = burnin, 
       iter = iterations)
5: withCallingHandlers(expr, warning = function(w) if (inherits(w, 
       classes)) tryInvokeRestart("muffleWarning"))
4: suppressWarnings(limSolve::xsample(G = G, H = h, E = E, F = f, 
       burninlength = burnin, iter = iterations))
3: musoRand(parameters = parameters, fileType = "epc", iterations = iterations)
2: musoMonte(parameters = parameters, settings = settings, inputDir = inputDir, 
       outLoc = outLoc, iterations = iterations, preTag = preTag, 
       outputType = outputType, outVars = outVars, fun = fun, varIndex = varIndex, 
       skipSpinup = skipSpinup, skipZero = skipZero, postProcString = postProcString, 
       modifyOut = modifyOut)
1: musoSensi(iterations = 10000, varIndex = 2)

**Comment by hollorol** [comment]
Thanks! It's a helpful results. I already have an idea what can be the problem. I can test it tomorrow.

**Comment by 857687671** [comment]
Thank you very much for your help! I'm a beginner. &nbsp;I've tried to solve this problem for a long time, but I couldn't solve it. I'm looking forward to your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hollorol/RBBGCMuso"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 凌晨2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hollorol/RBBGCMuso] Error with musoSensi (#13)





 
Thanks! It's a helpful results. I already have an idea what can be the problem. I can test it tomorrow.

**Comment by hollorol** [comment]
Good news here: the problem was with the most recent changes I made. Now it is obvious, that this is a bug. I'll fix it as soon as possible. You used the package correctly.

**Comment by hollorol** [comment]
I solved the issue. :) Thank you very much for your contribution! You should reinstall the R package :)

**Comment by 857687671** [comment]
Thank you very much for your help!I will try this again as soon as possible. If there is any problem, I will give you feedback. Thank you again!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hollorol/RBBGCMuso"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 晚上10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hollorol/RBBGCMuso] Error with musoSensi (#13)





 
I solved the issue. :) Thank you very much for your contribution! You should reinstall the R package :)
