### ISSUE TITLE
paramSweep and musosensi

### ISSUE THREAD

**Issue by science-explore** [hollorol/RBBGCMuso#18]
I am a student who is very interested in ecology. I am very interested in your work. I am currently trying to test. 
I have an immature question, paramSweep and musosensi，are there any differences between these two functions？and why should they be developed separately? 
I understand that they are also used to obtain the parameters with the smallest error from the actual results. Otherwise, I can’t think of the difference.

**Comment by zbarcza** [comment]
Hello

Check this for answers

https://github.com/hollorol/RBBGCMuso/issues/18#issuecomment-945579022

Cheers,
Zoltan

science-explore wrote:
