### ISSUE TITLE
Precipitation changes caused by EPC file changes

### ISSUE THREAD

**Issue by ghost** [hollorol/RBBGCMuso#29]
Hello,

Thank you for your package and model! I'm testing the version 6 in R since a few months and I have just upgraded to the verison 7.

I noticed a strange thing. I'm comparing two simulations using the same weather data, s.ini and n.ini files, but one simulation uses grass and the other DBF.

Keeping all the input files identical and only changing the EPC file, the outputs about precipitation (prcp_src and inW) changes depending on the EPC files. I didn't have this problem with the version 6.

I have tested by running the two simulations both with grass and in this case the precipitation outputs are identical. But if I change the EPC file of one simulation, then the precipitation outputs changes (it becomes higher for EBF than for grass by about 9% in my case). 

Could it be a bug in the new version?

**Comment by zbarcza** [comment]
Hello,

We are happy to see that you are using RBBGCMuso. 
The issue you descibe is not a strange thing. In fact this is pretty much logical and it is according to the expectations. prcp_src is precipitation minus runoff, but not precipitation itself. Runoff depends on soil water content, and soil water content depends on the simlated ecosystem. It means that runoff thus prcp_src changes if you change the EPC. 

I hope that this clarifies the issue.

Cheers,
Zoltan

**Comment by ghost** [comment]
Thanks for your explanation, I thought prcp_src was total precipitation indeed. The issue can be closed then.

Otherwise the simulated values compare quite well in temperate regions with observed satellite ET and GPP, even without calibration, this is great.

If I could just make a suggestion unrelated to this issue while I'm writing, it would be to add the ability to make RCN dynamic depending on the development of the forest (or other biomes).

For example in my case, I use grass for the spin-up and then forest with a RCN of e.g. 60 for the simulation. During the first few years, probably RCN should starts higher than 60 and decreases as the forest grows. Also during the dormant period for deciduous forest, RCN should increase. I think RCN can be adjusted in relation to e.g. the soil Antecedent Moisture Condition (AMC) and LAI. It would also be useful in seasonal analyses.

Great work anyway. All the best

**Comment by zbarcza** [comment]
I am glad that this is clarified. 
As for dynamic RCN I am not sure if it is needed. Runoff is just one components of the water cycle. Once runoff is removed from incominf precipitation (and canopy interception is considered), infiltration and soil water balance calculation starts where infltration depends on actual SWC. So in fact infiltration and the entire water cycle depends on LAI and (interception) and antecedent conditions (SWC). For a more precise description please check our latest soil development related paper: 

https://gmd.copernicus.org/articles/15/2157/2022/

See e.g. this part:
"Surface runoff is the water flow occurring on the surface
when a portion of the precipitation cannot infiltrate into the
soil. Two types of surface runoff processes can be distinguished:
Hortonian and Dunne. Hortonian runoff is unsaturated
overland flow that occurs when the rate of precipitation
exceeds the rate at which water can infiltrate. The other type
of surface runoff is the Dunne runoff (also known as the saturation
overland flow), which occurs when the entire soil is
saturated but the rain continues to fall. In this case the rainfall
immediately triggers pond water formation and (above
the maximum pond water height) surface runoff. The handling
of these processes is presented in the soil hydrological
module of Biome-BGCMuSo v6.2.
Calculation of Hortonian runoff (kgH2Om􀀀2 d􀀀1) is
based on a semi-empirical method and uses the precipitation
amount (cmd􀀀1), the unitless runoff curve number (RCN),
and the actual moisture content status of the topsoil (Rawls
et al., 1980; this method is known as the SCS runoff curve
number method; SCS: soil conservation service). This type
of runoff simulation can be turned off by setting RCN to zero.
A detailed description can be found in Sect. S1 in the Sup-
plement. The amount of runoff as a function of the soil type
and the actual SWC is presented in Fig. 1."

**Comment by ghost** [comment]
Thanks a lot, I will read it.
All the best
