### ISSUE TITLE
problem with different muso.exe version

### ISSUE THREAD

**Issue by zhengjiji456** [hollorol/RBBGCMuso#8]
I tried to use the muso4.1.exe with the package, but failed.

Error in (outIndex + 1):(outIndex + numVar) : NA/NaN argument
In addition: Warning messages:
1: In readLines(x, -1) :
  incomplete final line found on 'D:\BIOME-BGC\muso4.1\/s.ini'
2: In readLines(x, -1) :
  incomplete final line found on 'D:\BIOME-BGC\muso4.1\/n.ini'

The muso4.1.exe  worked well with s.ini/n.ini out of Rstudio.
I am not sure the package (0.6.3.0) is just suitable for the newest version of muso.exe?

**Comment by hollorol** [comment]
Did you use the setupMuso() function? You can set the model version with that.

**Comment by zhengjiji456** [comment]
Yes, I used the setupMuso() function.
