### ISSUE TITLE
Error is thrown for a given parameters.csv

### ISSUE THREAD

**Issue by dorakra** [hollorol/RBBGCMuso#9]
parameters.csv: 
NAME,INDEX,MIN,MAX
CGP,227,0.3000,0.9000

command:
./musoRand.sh c3grass_apriori_MuSo5.epc EPC 10
[c3grass_apriori_MuSo5.epc.zip](https://github.com/hollorol/RBBGCMuso/files/3387187/c3grass_apriori_MuSo5.epc.zip)

Result:
R version 3.3.3 (2017-03-06) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> RBBGCMuso::randEpc(sourceEpc = "c3grass_apriori_MuSo5.epc", iterations = 10, location = "EPC")
Error in data.frame(..., check.names = FALSE) :
  arguments imply differing number of rows: 0, 2
Calls: <Anonymous> -> musoRand -> cbind -> cbind -> data.frame
In addition: Warning message:
no DISPLAY variable so Tk is not available
Execution halted

**Comment by hollorol** [comment]
Solved
